### PR TITLE
Add integration testing

### PR DESCRIPTION
**Pull request by mcary**
This pull request adds integration testing by putting a rails app in spec/rails_app, like Devise itself does.

I also did a bit of clean up to the code base, including fixing broken specs and re-indenting.

This app does not currently have Devise or Devise Capturable installed.

### CODE REVIEW

**Comment by ruralocity** [comment]
I had to add the directory spec/rails_app/db for the specs to run; otherwise got sqlite errors trying to connect to or create a database.

**Comment by ruralocity** [comment]
Other than the questions/comments noted above, this looks good to me.

**Comment by mcary** [comment]
I've addressed the spec/rails_app/db issue with 16dae27.

**Comment by ruralocity** [comment]
One more thing I noticed: spec/rails_app/log/*.log should probably be ignored by git.

**Comment by ruralocity** [comment]
Also, spec/rails_app/db/*.sqlite3

**Pull request merged**
